import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import { getAuth, setPersistence, browserLocalPersistence, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut as firebaseSignOut } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import { initializeFirestore, persistentLocalCache, persistentMultipleTabManager, collection, doc, setDoc, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WORK_DAYS=[1,2,4,5];
const CALL_PLAN=[[9,'Active Buyer Follow-Up','Hot buyers, offers and contracts'],[10,'Past OFI Follow-Up','Recent attendees and missed callbacks'],[11,'Pipeline Calls','Current sellers and next-step conversations'],[12,'Past Appraisals','Owners with a likely 3–12 month move'],[13,'Database Reconnects','Long-term owners and dormant contacts'],[14,'Just Listed & Coming Soon','Create buyer and neighbour awareness'],[15,'Just Sold Calls','Result calls and nearby owner follow-up'],[16,'Priority Follow-Up','Offers, appointments and tomorrow’s pipeline']];
const DEFAULTS={calls:50,connects:25,data:10,weeklyKnock:240,breakReminder:true};
let targets={...DEFAULTS},days={},uid='local',cloud=false,db=null,auth=null,unsubscribe=null,selectedDate=dateKey(new Date()),appointmentDate=selectedDate,year=new Date().getFullYear(),monthCursor=new Date(),timerTick=null,breakAlerted=false;

function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function parseKey(k){const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)}
function mondayOf(d){const x=new Date(d),day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));x.setHours(0,0,0,0);return x}
function dayData(k){return days[k]||{calls:0,connects:0,data:0,knockSeconds:0,timerStartedAt:null,events:[],appointments:[],review:{},updatedAt:0}}
function haptic(ms=10){navigator.vibrate?.(ms)}
function pct(n,t){return Math.min(100,Math.round((n/Math.max(1,t))*100))}
function weekKeys(d=new Date()){const m=mondayOf(d);return WORK_DAYS.map(offset=>{const x=new Date(m);x.setDate(m.getDate()+offset-1);return dateKey(x)})}
function liveKnockSeconds(d){let s=d.knockSeconds||0;if(d.timerStartedAt)s+=Math.max(0,Math.floor((Date.now()-d.timerStartedAt)/1000));return s}
function rollingKnockTarget(k){const date=parseKey(k),monday=mondayOf(date);let prior=0,seen=0;for(const offset of WORK_DAYS){const x=new Date(monday);x.setDate(monday.getDate()+offset-1);const key=dateKey(x);if(key===k)break;prior+=Math.floor(liveKnockSeconds(dayData(key))/60);seen++}return Math.ceil(Math.max(0,targets.weeklyKnock-prior)/Math.max(1,WORK_DAYS.length-seen))}
function completion(k){const d=dayData(k),kt=rollingKnockTarget(k);return Math.round((pct(d.calls,targets.calls)+pct(d.connects,targets.connects)+pct(d.data,targets.data)+pct(liveKnockSeconds(d)/60,kt))/4)}
function fmtDate(k){return parseKey(k).toLocaleDateString('en-AU',{weekday:'long',day:'numeric',month:'long'})}
function fmtTimer(sec){const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=Math.floor(sec%60);return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function id(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function configured(){return firebaseConfig.apiKey&&!firebaseConfig.apiKey.startsWith('PASTE_')}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}

function loadLocal(){try{days=JSON.parse(localStorage.getItem('da-days-v4')||localStorage.getItem('da-days-v3')||'{}');targets={...DEFAULTS,...JSON.parse(localStorage.getItem('da-targets-v4')||localStorage.getItem('da-targets-v3')||'{}')}}catch{days={}}}
function saveLocal(){localStorage.setItem('da-days-v4',JSON.stringify(days));localStorage.setItem('da-targets-v4',JSON.stringify(targets))}
async function saveDay(k){days[k]={...dayData(k),updatedAt:Date.now()};saveLocal();renderAll();if(cloud)await setDoc(doc(db,'users',uid,'days',k),days[k],{merge:true})}
async function saveTargets(){saveLocal();if(cloud)await setDoc(doc(db,'users',uid),{targets,updatedAt:serverTimestamp()},{merge:true})}
function addEvent(d,type,label,delta=1,meta={}){d.events=[...(d.events||[]),{id:id(),type,label,delta,at:Date.now(),...meta}].slice(-1000)}
async function changeMetric(metric,delta){const d={...dayData(selectedDate),events:[...(dayData(selectedDate).events||[])]};d[metric]=Math.max(0,(d[metric]||0)+delta);addEvent(d,metric,`${metric[0].toUpperCase()+metric.slice(1)} ${delta>0?'+1':'−1'}`,delta);days[selectedDate]=d;haptic();await saveDay(selectedDate)}

async function toggleTimer(){const d={...dayData(selectedDate),events:[...(dayData(selectedDate).events||[])]};if(d.timerStartedAt){d.knockSeconds=liveKnockSeconds(d);d.timerStartedAt=null;addEvent(d,'knock','Knocking paused',0,{seconds:d.knockSeconds})}else{d.timerStartedAt=Date.now();breakAlerted=false;let geo=null;try{geo=await new Promise((res,rej)=>navigator.geolocation?.getCurrentPosition(p=>res({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),rej,{enableHighAccuracy:false,timeout:5000}))}catch{}addEvent(d,'knock','Knocking started',0,geo?{location:geo}:{})}days[selectedDate]=d;haptic(18);await saveDay(selectedDate);ensureTick()}
async function addFive(){const d={...dayData(selectedDate),events:[...(dayData(selectedDate).events||[])],knockSeconds:liveKnockSeconds(dayData(selectedDate))+300,timerStartedAt:null};addEvent(d,'knock','Knocking +5 minutes',300,{seconds:d.knockSeconds});days[selectedDate]=d;await saveDay(selectedDate)}
function ensureTick(){clearInterval(timerTick);if(dayData(selectedDate).timerStartedAt)timerTick=setInterval(()=>{renderToday();const d=dayData(selectedDate),sec=liveKnockSeconds(d),target=rollingKnockTarget(selectedDate)*60;if(sec>=target&&!d.alarmPlayed){d.alarmPlayed=true;days[selectedDate]=d;saveDay(selectedDate);alarm('Daily knocking target reached')}if(targets.breakReminder&&sec>=3000&&!breakAlerted){breakAlerted=true;notify('50 minutes complete','Take a short reset, then finish strong.')}},1000)}
function alarm(message){haptic([200,100,200]);toast(message);try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=880;g.gain.setValueAtTime(.18,c.currentTime);o.start();o.stop(c.currentTime+.6)}catch{}}
async function notify(title,body){if('Notification'in window){if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission==='granted')new Notification(title,{body,icon:'icons/icon-192.png'})}toast(title)}

function formatHour(h){return `${h%12||12}:00 ${h>=12?'PM':'AM'}`}
function renderCallPlan(){const hour=new Date().getHours();let current=CALL_PLAN.find(x=>x[0]===hour);if(hour<9)current=[8,'Prepare your priority list','Before 9:00 AM'];if(hour>=17)current=[17,'Wrap-up and tomorrow’s priorities','After 5:00 PM'];$('#currentCall').textContent=current[1];$('#currentSlot').textContent=hour>=9&&hour<17?`${formatHour(hour)}–${formatHour(hour+1)} · 10 call target`:current[2];$('#callPlan').innerHTML=CALL_PLAN.map(([h,title,note])=>`<div class="call-row ${h===hour?'active':''}"><b>${formatHour(h)}</b><span><strong>${title}</strong><small>${note}</small></span><em>10</em></div>`).join('')}
function callsPaceText(value){const h=new Date().getHours()+new Date().getMinutes()/60;if(h<9)return `${targets.calls-value} remaining`;if(h>=17)return value>=targets.calls?'Target complete':`${targets.calls-value} short today`;const expected=Math.min(targets.calls,Math.round((h-9)*10)),diff=value-expected;return diff===0?'On pace':diff>0?`${diff} ahead of pace`:`${Math.abs(diff)} behind pace`}
function renderToday(){const d=dayData(selectedDate),score=completion(selectedDate),kt=rollingKnockTarget(selectedDate);$('#dateLabel').textContent=fmtDate(selectedDate);$('#dailyScore').textContent=`${score}%`;$('#scoreBar').style.width=`${score}%`;$('#streak').textContent=streak();for(const m of ['calls','connects','data']){$(`#${m}Value`).textContent=d[m]||0;$(`#${m}TargetLabel`).textContent=`/${targets[m]}`;const rem=Math.max(0,targets[m]-(d[m]||0));$(`#${m}Pace`).textContent=m==='calls'?callsPaceText(d[m]||0):(rem?`${rem} remaining`:'Target complete');document.querySelector(`[data-metric="${m}"]`).classList.toggle('complete',rem===0)}const secs=liveKnockSeconds(d);$('#knockValue').textContent=fmtTimer(secs);$('#knockTarget').textContent=`${kt} min today · ${Math.floor(weekKnock()/60)}/${targets.weeklyKnock} weekly`;$('#timerButton').textContent=d.timerStartedAt?'Pause':'Start';$('#timerButton').classList.toggle('running',!!d.timerStartedAt);const wk=weekSummary();$('#weekScore').textContent=`${wk.score}%`;$('#weekKnock').textContent=`${Math.floor(wk.knock/60)}/${targets.weeklyKnock}m`;renderCallPlan()}
function weekSummary(base=parseKey(selectedDate)){const ks=weekKeys(base);let calls=0,connects=0,data=0,knock=0;ks.forEach(k=>{const d=dayData(k);calls+=d.calls||0;connects+=d.connects||0;data+=d.data||0;knock+=liveKnockSeconds(d)});return{calls,connects,data,knock,score:Math.round((pct(calls,targets.calls*4)+pct(connects,targets.connects*4)+pct(data,targets.data*4)+pct(knock/60,targets.weeklyKnock))/4)}}
function weekKnock(){return weekSummary().knock}
function streak(){let n=0,d=new Date();for(let i=0;i<500;i++){if(WORK_DAYS.includes(d.getDay())){const k=dateKey(d);if(k===dateKey(new Date())&&completion(k)<100){d.setDate(d.getDate()-1);continue}if(completion(k)>=100)n++;else break}d.setDate(d.getDate()-1)}return n}

function renderAppointments(){appointmentDate=$('#appointmentDatePicker').value||appointmentDate;$('#appointmentDateLabel').textContent=fmtDate(appointmentDate);const items=[...(dayData(appointmentDate).appointments||[])].sort((a,b)=>b.createdAt-a.createdAt);$('#appointmentsList').innerHTML=items.length?items.map(a=>`<article class="appointment-card"><div><strong>${a.address}</strong><small>${a.types.join(' · ')}</small></div><button data-delete-appointment="${a.id}" aria-label="Delete appointment">×</button></article>`).join(''):'<div class="empty">No appointments logged for this date.</div>'}
async function addAppointment(address,types){const d={...dayData(appointmentDate),events:[...(dayData(appointmentDate).events||[])],appointments:[...(dayData(appointmentDate).appointments||[])]};d.appointments.push({id:crypto.randomUUID?.()||String(Date.now()),address,types,createdAt:Date.now()});days[appointmentDate]=d;await saveDay(appointmentDate);renderAppointments();toast('Appointment added')}
async function deleteAppointment(id){const d={...dayData(appointmentDate),appointments:[...(dayData(appointmentDate).appointments||[])]};d.appointments=d.appointments.filter(a=>a.id!==id);days[appointmentDate]=d;await saveDay(appointmentDate);renderAppointments()}
function renderInsights(){const w=weekSummary(),pb=personalBests();$('#insightWeekScore').textContent=`${w.score}%`;$('#insightWeekLabel').textContent=`Week of ${mondayOf(parseKey(selectedDate)).toLocaleDateString('en-AU',{day:'numeric',month:'short'})}`;$('#insightCalls').textContent=w.calls;$('#insightCallsAvg').textContent=`${Math.round(w.calls/4)}/day`;$('#insightConnects').textContent=w.connects;$('#insightConnectRate').textContent=`${w.calls?Math.round(w.connects/w.calls*100):0}% connect rate`;$('#insightData').textContent=w.data;$('#insightDataAvg').textContent=`${Math.round(w.data/4)}/day`;$('#insightKnock').textContent=`${Math.floor(w.knock/60)} min`;$('#knockBar').style.width=`${pct(w.knock/60,targets.weeklyKnock)}%`;$('#personalBests').innerHTML=`<div><b>${pb.calls}</b><small>calls/day</small></div><div><b>${pb.connects}</b><small>connects/day</small></div><div><b>${pb.knock}m</b><small>knocking/day</small></div>`;renderMonth();$('#yearLabel').textContent=year;$('#yearHeatmap').innerHTML='';for(let d=new Date(year,0,1);d<new Date(year+1,0,1);d.setDate(d.getDate()+1)){const i=document.createElement('i'),p=completion(dateKey(d));i.className=p===100?'l4':p>=67?'l3':p>=34?'l2':p>0?'l1':'';i.title=`${dateKey(d)} · ${p}%`;$('#yearHeatmap').append(i)}}
function renderMonth(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth();$('#monthLabel').textContent=monthCursor.toLocaleDateString('en-AU',{month:'long',year:'numeric'});const vals=[];for(let d=1;d<=new Date(y,m+1,0).getDate();d++){const dt=new Date(y,m,d);if(WORK_DAYS.includes(dt.getDay()))vals.push({day:d,p:completion(dateKey(dt))})}const groups=[];for(let i=0;i<vals.length;i+=4){const g=vals.slice(i,i+4);groups.push({label:`W${groups.length+1}`,p:Math.round(g.reduce((s,x)=>s+x.p,0)/Math.max(1,g.length))})}$('#monthBars').innerHTML=groups.map(g=>`<div title="${g.p}%"><i style="height:${Math.max(3,g.p)}%"></i><small>${g.label}</small></div>`).join('')}
function renderCalendar(){$('#calendarYear').textContent=year;const months=[];for(let m=0;m<12;m++){let cells='<div class="days">',first=new Date(year,m,1),pad=(first.getDay()+6)%7;cells+='<i></i>'.repeat(pad);for(let d=1;d<=new Date(year,m+1,0).getDate();d++){const k=dateKey(new Date(year,m,d)),p=completion(k),cl=p===100?'l4':p>=67?'l3':p>=34?'l2':p>0?'l1':'';cells+=`<button class="daydot ${cl}" data-date="${k}" title="${p}%"></button>`}cells+='</div>';months.push(`<section class="month"><h3>${new Date(year,m,1).toLocaleDateString('en-AU',{month:'long'})}</h3>${cells}</section>`)}$('#calendarGrid').innerHTML=months.join('')}
function renderSettings(){$('#callsTarget').value=targets.calls;$('#connectsTarget').value=targets.connects;$('#dataTarget').value=targets.data;$('#weeklyKnockTarget').value=targets.weeklyKnock;$('#breakReminder').checked=!!targets.breakReminder;$('#modeNote').textContent=cloud?'Live sync is on. Changes update across signed-in devices.':'Local mode: data is saved only on this device.'}
function renderAll(){renderToday();renderAppointments();renderInsights();renderSettings()}

async function startCloud(user){uid=user.uid;cloud=true;$('#syncBtn').textContent='Live';$('#syncBtn').classList.add('online');unsubscribe?.();unsubscribe=onSnapshot(collection(db,'users',uid,'days'),snap=>{snap.docChanges().forEach(ch=>{if(ch.type==='removed')delete days[ch.doc.id];else days[ch.doc.id]=ch.doc.data()});saveLocal();renderAll();ensureTick()},()=>{$('#syncBtn').textContent='Offline cache';$('#syncBtn').classList.remove('online')});onSnapshot(doc(db,'users',uid),s=>{if(s.exists()&&s.data().targets){targets={...DEFAULTS,...s.data().targets};saveLocal();renderAll()}});showApp()}
function showApp(){loadLocal();$('#authGate').classList.add('hidden');$('#app').classList.remove('hidden');$('#appointmentDatePicker').value=appointmentDate;renderAll();ensureTick()}
async function init(){loadLocal();if(!configured()){showAuthMessage('Firebase is not configured yet. Local mode is available.');return}try{const app=initializeApp(firebaseConfig);auth=getAuth(app);await setPersistence(auth,browserLocalPersistence);db=initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})});onAuthStateChanged(auth,u=>u?startCloud(u):$('#authGate').classList.remove('hidden'))}catch(e){showAuthMessage(e.message)}}
function showAuthMessage(m){$('#authMessage').textContent=m}

function switchView(id){$$('.tabbar button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));const b=document.querySelector(`.tabbar button[data-view="${id}"]`);$('#viewTitle').textContent=b?.querySelector('span')?.textContent||'Today';if(id==='appointmentsView')renderAppointments();if(id==='insightsView')renderInsights()}
function voiceLog(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return toast('Voice logging is not supported in this browser');const r=new SR();r.lang='en-AU';r.interimResults=false;r.onresult=e=>{const t=e.results[0][0].transcript.toLowerCase();let metric=t.includes('connect')?'connects':t.includes('data')?'data':t.includes('call')?'calls':null;const n=parseInt(t.match(/\d+/)?.[0]||'1',10);if(metric){for(let i=0;i<n;i++)changeMetric(metric,1);toast(`Logged ${n} ${metric}`)}else if(t.includes('start knocking'))toggleTimer();else if(t.includes('stop knocking')||t.includes('pause knocking'))toggleTimer();else toast('Try “log 3 calls” or “start knocking”')};r.onerror=()=>toast('Voice logging could not start');r.start()}

$('#authForm').addEventListener('submit',async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('#email').value,$('#password').value)}catch(err){showAuthMessage(err.message)}});$('#createAccount').onclick=async()=>{if(!configured())return showAuthMessage('Add Firebase configuration first.');try{await createUserWithEmailAndPassword(auth,$('#email').value,$('#password').value)}catch(err){showAuthMessage(err.message)}};$('#localMode').onclick=()=>{cloud=false;uid='local';$('#syncBtn').textContent='Local';showApp()};$$('[data-action]').forEach(b=>b.onclick=()=>changeMetric(b.dataset.metric,b.dataset.action==='plus'?1:-1));$('#timerButton').onclick=toggleTimer;$('#addKnock').onclick=addFive;$('#voiceBtn').onclick=voiceLog;$('#settingsShortcut').onclick=()=>switchView('settingsView');
$('.tabbar').onclick=e=>{const b=e.target.closest('button[data-view]');if(b)switchView(b.dataset.view)};$('#appointmentDatePicker').onchange=e=>{appointmentDate=e.target.value;renderAppointments()};$('#appointmentForm').onsubmit=async e=>{e.preventDefault();const address=$('#appointmentAddress').value.trim();const types=[...document.querySelectorAll('.appointment-types input:checked')].map(x=>x.value);if(!address)return toast('Add a property address');if(!types.length)return toast('Choose an appointment type');await addAppointment(address,types);e.target.reset()};$('#appointmentsList').onclick=e=>{const b=e.target.closest('[data-delete-appointment]');if(b&&confirm('Delete this appointment?'))deleteAppointment(b.dataset.deleteAppointment)};
$('#saveSettings').onclick=async()=>{targets={calls:+$('#callsTarget').value||50,connects:+$('#connectsTarget').value||25,data:+$('#dataTarget').value||10,weeklyKnock:+$('#weeklyKnockTarget').value||240,breakReminder:$('#breakReminder').checked};await saveTargets();renderAll();haptic(20);toast('Settings saved')};$('#signOut').onclick=async()=>{if(cloud)await firebaseSignOut(auth);cloud=false;location.reload()};$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({targets,days},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`daily-accountability-${dateKey(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importData').onchange=async e=>{try{const raw=JSON.parse(await e.target.files[0].text());targets={...DEFAULTS,...raw.targets};days={...days,...raw.days};saveLocal();if(cloud){await saveTargets();for(const k of Object.keys(raw.days||{}))await saveDay(k)}renderAll();toast('Backup imported')}catch{toast('That backup file could not be read')}};
$('#openCalendar').onclick=()=>{$('#calendarModal').classList.add('open');renderCalendar()};$('#closeCalendar').onclick=()=>$('#calendarModal').classList.remove('open');$('#calendarPrev').onclick=$('#prevYear').onclick=()=>{year--;renderCalendar();renderInsights()};$('#calendarNext').onclick=$('#nextYear').onclick=()=>{year++;renderCalendar();renderInsights()};$('#calendarGrid').onclick=e=>{const b=e.target.closest('[data-date]');if(!b)return;selectedDate=b.dataset.date;appointmentDate=selectedDate;$('#appointmentDatePicker').value=appointmentDate;$('#calendarModal').classList.remove('open');renderAll();ensureTick()};$('#prevMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()-1);renderMonth()};$('#nextMonth').onclick=()=>{monthCursor.setMonth(monthCursor.getMonth()+1);renderMonth()};$('#printReport').onclick=()=>window.print();
$('#reviewBtn').onclick=()=>{const r=dayData(selectedDate).review||{};$('#reviewWins').value=r.wins||'';$('#reviewFollowup').value=r.followup||'';$('#reviewPriority').value=r.priority||'';$('#reviewModal').classList.add('open')};$('#closeReview').onclick=()=>$('#reviewModal').classList.remove('open');$('#reviewForm').onsubmit=async e=>{e.preventDefault();const d={...dayData(selectedDate),events:[...(dayData(selectedDate).events||[])]};d.review={wins:$('#reviewWins').value.trim(),followup:$('#reviewFollowup').value.trim(),priority:$('#reviewPriority').value.trim(),savedAt:Date.now()};addEvent(d,'review','End-of-day review saved',0);days[selectedDate]=d;await saveDay(selectedDate);$('#reviewModal').classList.remove('open');toast('Review saved')};
window.addEventListener('online',()=>{$('#syncBtn').textContent=cloud?'Live':'Local';$('#syncBtn').classList.toggle('online',cloud)});window.addEventListener('offline',()=>{$('#syncBtn').textContent='Offline cache';$('#syncBtn').classList.remove('online')});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));init();
