// v1.41.30: focused async ranking/presentation/session regression checks.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/app.js','utf8');
function fn(name){const m=new RegExp('(?:async )?function '+name+'\\(').exec(source);assert(m,name);const tail=source.slice(m.index),end=tail.slice(1).search(/\n(?:async )?function /);return end<0?tail:tail.slice(0,end+1)}
(async()=>{
const timers=new Map(),frames=[];let timerId=0;const today='2026-09-15',cache={ready:true,uid:'a',day:today,value:{eventId:'seller-a',title:'Call A',sellerPriority:true},expiresAt:Date.now()+10000};
const c={console,Date,Math,Number,String,Map,uid:'a',selectedDate:today,todayKey:()=>today,prospects:[{id:'seller-a',name:'A',phone:'04',sellingTimeframe:'Now'}],prospectInteractions:[],sellerPriorityCache:cache,sellerPriorityImmediateDeferrals:new Map(),sellerPriorityBuildToken:0,sellerPriorityBuilding:false,sellerPriorityRefreshRequested:false,sellerPriorityRefreshTimer:null,primaryProspectPhone:p=>p.phone,prospectById:id=>c.prospects.find(p=>p.id===id),clearTimeout:id=>timers.delete(id),setTimeout:(f)=>{timers.set(++timerId,f);return timerId},requestAnimationFrame:f=>frames.push(f)};vm.createContext(c);
for(const name of ['sellerPriorityTieBreak','validCachedSellerPriority','scheduleSellerPriorityRefresh','invalidateSellerPriorityCache','sellerNextBestAction','rebuildSellerPriorityCache'])vm.runInContext(fn(name),c);
c.invalidateSellerPriorityCache();assert.equal(c.sellerNextBestAction().eventId,'seller-a');assert.equal(timers.size,1);c.invalidateSellerPriorityCache();assert.equal(c.sellerNextBestAction().eventId,'seller-a');assert.equal(timers.size,1);
c.prospectInteractions=[{prospectId:'seller-a',type:'Call',date:today}];assert.equal(c.sellerNextBestAction(),null);c.prospectInteractions=[];c.sellerPriorityImmediateDeferrals.set('seller-a',Date.now()+100000);assert.equal(c.sellerNextBestAction(),null);c.sellerPriorityImmediateDeferrals.clear();c.uid='b';assert.equal(c.sellerNextBestAction(),null);c.uid='a';c.sellerPriorityCache.day='2026-09-14';assert.equal(c.sellerNextBestAction(),null);c.sellerPriorityCache.day=today;
let renders=0;Object.assign(c,{sellerPriorityYield:async()=>{},sellerPriorityBuildContext:async()=>({marketByStreet:new Map()}),activeProspects:()=>c.prospects,sellerPriorityCandidatePreRank:()=>100,SELLER_PRIORITY_MAX_CANDIDATES:2500,SELLER_PRIORITY_CHUNK_SIZE:100,sellerPriorityCandidate:p=>({prospect:p,score:60,reasons:['Hot seller'],purpose:'seller conversation'}),$:()=>({classList:{contains:()=>false}}),renderNowCard:()=>renders++,renderTimeline(){}});
c.prospects=[{id:'seller-b',name:'B',phone:'04',sellingTimeframe:'Now'},{id:'seller-a',name:'A',phone:'04',sellingTimeframe:'Now'}];await c.rebuildSellerPriorityCache(c.sellerPriorityBuildToken);assert.equal(c.sellerPriorityCache.value.eventId,'seller-a');c.prospects.reverse();await c.rebuildSellerPriorityCache(c.sellerPriorityBuildToken);assert.equal(c.sellerPriorityCache.value.eventId,'seller-a');c.invalidateSellerPriorityCache({schedule:false});frames.splice(0).forEach(f=>f());assert.equal(renders,0);
// Cancel a yielded calculation on reset; it must not publish or schedule itself again.
let release;c.sellerPriorityYield=()=>new Promise(resolve=>release=resolve);const old=c.rebuildSellerPriorityCache(c.sellerPriorityBuildToken);c.invalidateSellerPriorityCache({schedule:false});release();await old;assert.equal(c.sellerPriorityCache.value,null);assert.equal(timers.size,0);
// Cold startup shows neutral text until ranking completes; appointments still take precedence.
Object.assign(c,{isWorkDayKey:()=>true,cleanText:x=>String(x||''),prospectSessionContext:{},prospectSessionActive:false,dailyCommandFromItem:item=>({title:item.title}),dailyCommandItemRank:()=>0,legacyMetricCoachingEngine:()=>({title:'Plan today'}),legacyTimelineItemsForDate:()=>[]});vm.runInContext(fn('dailyCommandPriority'),c);
assert.equal(c.dailyCommandPriority(today,[],new Date('2026-09-15T10:00:00')).title,'Loading today…');
assert.equal(c.dailyCommandPriority(today,[{kind:'appointment',minutes:600,duration:60,title:'Appointment'}],new Date('2026-09-15T10:00:00')).title,'Appointment');
c.sellerPriorityCache.ready=true;c.sellerPriorityCache.expiresAt=Date.now()+100000000000;assert.equal(c.dailyCommandPriority(today,[],new Date('2026-09-15T10:00:00')).title,'Plan today');
// Unchanged priority does not replace live text nodes.
let writes=0;const nodes={};for(const id of ['#nowCardLabel','#nowCardTitle','#nowCardMeta']){let value='';nodes[id]={get textContent(){return value},set textContent(v){writes++;value=v}}}nodes['#openTodayTimeline']={dataset:{},getAttribute:()=>'',setAttribute(){}};Object.assign(c,{$:s=>nodes[s],timelinePriority:()=>({title:'Call A',meta:'Due today',kicker:'SELLER PRIORITY',action:'open-seller',eventId:'seller-a'})});vm.runInContext(fn('renderNowCard'),c);c.renderNowCard();assert.equal(writes,3);c.renderNowCard();assert.equal(writes,3);assert.equal(nodes['#openTodayTimeline'].dataset.eventId,'seller-a');
// Old prospecting acknowledgements must not release the new account's write lock/dirty marker.
let resolveWrite,dirtyClears=0,waiterResolved=0;Object.assign(c,{cloud:true,db:{},uid:'a',currentUser:{uid:'a'},prospectingSaveTimer:null,prospectingWriteInFlight:false,pendingProspectingPayload:{prospects:[]},pendingProspectingSignature:'a-write',pendingProspectingRevision:1,prospectingSaveWaiters:[{resolve:()=>waiterResolved++,reject(){}}],lastProspectingSignature:'',beginSyncOperation(){},doc:()=>({}),serverTimestamp:()=>0,setDoc:()=>new Promise(resolve=>resolveWrite=resolve),clearProspectingDirty:()=>dirtyClears++,clearSyncError(){},endSyncOperation(){}});vm.runInContext(fn('flushProspectingSave'),c);const save=c.flushProspectingSave();c.uid='b';c.currentUser={uid:'b'};c.lastProspectingSignature='b-write';c.prospectingWriteInFlight=true;resolveWrite();await save;assert.equal(c.lastProspectingSignature,'b-write');assert.equal(c.prospectingWriteInFlight,true);assert.equal(dirtyClears,0);assert.equal(waiterResolved,1);
console.log('PASS: priority retained during refresh; immediate eligibility; stable ties; cancelled builds/paint; unchanged DOM text; prospecting account-switch completion isolation.');
})().catch(err=>{console.error(err);process.exitCode=1});
