// Dependency-free runtime regression checks for v1.41.29. No Firebase/network access.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/app.js','utf8');
function fn(name){const pattern=new RegExp('(?:async )?function '+name+'\\('),m=pattern.exec(source);assert(m,name);const tail=source.slice(m.index),next=tail.slice(1).search(/\n(?:async )?function /);return next<0?tail:tail.slice(0,next+1)}
(async()=>{
const styles={},classes=new Set(),ctx={console,Math,Number,viewportFrame:0,cancelAnimationFrame(){},requestAnimationFrame:f=>{f();return 1},document:{documentElement:{clientHeight:667,style:{setProperty:(k,v)=>styles[k]=v},classList:{toggle:(k,on)=>on?classes.add(k):classes.delete(k)}}},window:{matchMedia:()=>({matches:false}),navigator:{standalone:false},innerHeight:667,screen:{height:844},visualViewport:{height:667,offsetTop:0}}};vm.createContext(ctx);vm.runInContext(fn('updateAppViewport'),ctx);
for(const [w,h]of [[320,568],[375,667],[390,844],[430,932],[667,375]]){ctx.window.innerHeight=h;ctx.document.documentElement.clientHeight=h;ctx.window.visualViewport={height:h,offsetTop:0};ctx.updateAppViewport();assert.equal(styles['--app-height'],h+'px');assert.equal(styles['--visual-height'],h+'px')}
ctx.window.innerHeight=667;ctx.window.visualViewport={height:330,offsetTop:20};ctx.updateAppViewport();assert.equal(styles['--app-height'],'667px');assert.equal(styles['--visual-height'],'330px');assert.equal(styles['--visual-top'],'20px');assert(classes.has('keyboard-open'));
// Regression: iPhone installed shell must retain the pre-audit full-screen height.
ctx.window.navigator.standalone=true;ctx.window.innerHeight=884;ctx.document.documentElement.clientHeight=884;ctx.window.screen={height:956,availHeight:956};ctx.window.visualViewport={height:884,offsetTop:0};ctx.updateAppViewport();assert.equal(styles['--app-height'],'956px');assert.equal(styles['--sheet-height'],'956px');assert.equal(styles['--sheet-top'],'0px');assert(!classes.has('keyboard-open'));
ctx.window.visualViewport={height:420,offsetTop:40};ctx.updateAppViewport();assert.equal(styles['--app-height'],'956px');assert.equal(styles['--sheet-height'],'420px');assert.equal(styles['--sheet-top'],'40px');assert(classes.has('keyboard-open'));
ctx.window.matchMedia=q=>({matches:q==='(orientation: landscape)'});ctx.window.innerHeight=440;ctx.document.documentElement.clientHeight=440;ctx.window.visualViewport={height:440,offsetTop:0};ctx.updateAppViewport();assert.equal(styles['--app-height'],'440px');
ctx.window.matchMedia=()=>({matches:false});ctx.window.navigator.standalone=false;
const handlers={},docHandlers={};let suspends=0,resumes=0;Object.assign(ctx,{handleAppSuspend:()=>suspends++,scheduleAppResume:()=>resumes++});ctx.window.addEventListener=(n,f)=>handlers[n]=f;ctx.document.addEventListener=(n,f)=>docHandlers[n]=f;ctx.document.hidden=false;vm.runInContext(fn('bindAppLifecycle'),ctx);ctx.bindAppLifecycle();handlers.pageshow({persisted:false});handlers.focus();assert.equal(resumes,0);ctx.document.hidden=true;docHandlers.visibilitychange();handlers.pagehide();assert.equal(suspends,1);ctx.document.hidden=false;docHandlers.visibilitychange();handlers.focus();assert.equal(resumes,1);handlers.pageshow({persisted:true});assert.equal(resumes,2);
let renders=0,external=0;Object.assign(ctx,{startupReady:true,$:()=>({classList:{contains:()=>false}}),adoptCurrentDay:()=>false,resumePendingExternalAction:()=>external++,finaliseExpiredTimers:async()=>{},renderAll:()=>renders++,renderToday(){},renderTimeline(){},renderKnockTimerOnly(){},refreshSyncStatus(){},switchView(){}});vm.runInContext(fn('handleAppResume'),ctx);await ctx.handleAppResume();assert.equal(renders,0);assert.equal(external,1);
const submit={disabled:false,textContent:'Add task'},error={classList:{remove(){}},textContent:''},form={dataset:{},querySelector:()=>submit},day={tasks:[]};let fail=true,saves=0,closed=0;
Object.assign(ctx,{FormData:class{get(k){return{title:'Test task',note:'Long note',date:'2026-09-15',time:'09:00',assignedToUid:'tester'}[k]}},cleanText:(s)=>s,validDateKey:s=>/^\d{4}-\d{2}-\d{2}$/.test(s),todayKey:()=> '2026-09-15',uid:'tester',$:()=>error,appointmentAssignees:[],normaliseTaskRecord:x=>x,uuid:()=> 'stable-task',displayAgentName:()=> 'Tester',dayData:()=>day,days:{},saveDay:async(k,options)=>{saves++;assert.equal(options.awaitCloud,false);await Promise.resolve();if(fail)throw Error('Simulated storage failure')},closeTaskComposer:()=>closed++,renderTimeline(){},haptic(){},toast(){}});vm.runInContext(fn('addTaskFromForm'),ctx);ctx.console={error(){}};
const first=ctx.addTaskFromForm(form);await ctx.addTaskFromForm(form);await first;assert.equal(saves,1);assert.equal(submit.disabled,false);assert.equal(day.tasks.length,1);assert(error.textContent.includes('try again'));fail=false;await ctx.addTaskFromForm(form);assert.equal(day.tasks.length,1);assert.equal(closed,1);assert.equal(submit.textContent,'Add task');
const metrics={calls:0,connects:0,events:[]};ctx.dayData=()=>metrics;ctx.saveDay=async(k,o)=>assert.equal(o.awaitCloud,false);vm.runInContext(fn('applyManualCallOutcome'),ctx);await ctx.applyManualCallOutcome('Connected',{id:'call-1'});await ctx.applyManualCallOutcome('Connected',{id:'call-1'});assert.equal(metrics.calls,1);assert.equal(metrics.connects,1);await ctx.applyManualCallOutcome('Cancelled',{id:'call-2'});assert.equal(metrics.calls,1);
// A delayed day-save queue must never execute using a subsequent account's UID.
let unblock,cloudWrites=0;const held=new Promise(resolve=>unblock=resolve);
Object.assign(ctx,{cloud:true,uid:'account-a',currentUser:{uid:'account-a'},daySaveChains:new Map([['2026-09-15',held]]),days:{},dayData:()=>({calls:1}),markDayDirty(){},saveLocal(){},renderDayViews(){},persistDayToCloud:async()=>cloudWrites++});
vm.runInContext(fn('saveDay'),ctx);await ctx.saveDay('2026-09-15',{awaitCloud:false});const queued=ctx.daySaveChains.get('2026-09-15');ctx.uid='account-b';ctx.currentUser={uid:'account-b'};unblock();await queued;assert.equal(cloudWrites,0);
await ctx.saveDay('2026-09-15',{awaitCloud:false});await ctx.daySaveChains.get('2026-09-15');assert.equal(cloudWrites,1);
// A cloud completion from a previous account cannot clear the current account's dirty marker.
let resolveWrite,cleared=0;Object.assign(ctx,{db:{},setDoc:()=>new Promise(resolve=>resolveWrite=resolve),doc:()=>({}),serverTimestamp:()=>0,beginSyncOperation(){},endSyncOperation(){},clearDayDirty:()=>cleared++,scheduleLeaderboardPublish(){}});
vm.runInContext(fn('persistDayToCloud'),ctx);const staleWrite=ctx.persistDayToCloud('2026-09-15',{});ctx.uid='account-c';ctx.currentUser={uid:'account-c'};resolveWrite();await staleWrite;assert.equal(cleared,0);
// Exercise worker cache writes after response consumption, plus rejected cache writes.
const listeners={},writes=[],sw={console:{warn(){}},URL,Promise,self:{location:{origin:'https://agnt.test'},addEventListener:(n,f)=>listeners[n]=f},caches:{open:async()=>({put:async(k,r)=>writes.push(await r.text())}),match:async()=>null},fetch:async()=>new Response('cached body')};vm.createContext(sw);vm.runInContext(fs.readFileSync(__dirname+'/service-worker.js','utf8'),sw);
for(const mode of ['navigate','cors']){const waits=[];let response;listeners.fetch({request:{method:'GET',url:'https://agnt.test/'+mode,mode},respondWith:p=>response=p,waitUntil:p=>waits.push(p)});await(await response).text();await Promise.all(waits)}assert.deepEqual(writes,['cached body','cached body']);
console.log('PASS: viewport dimensions/keyboard offsets; lifecycle event coalescing; warm form preservation; task duplicate/error/retry; call metrics idempotency; account-switch queue isolation; service-worker response consumption.');
})().catch(e=>{console.error(e);process.exitCode=1});
